export const IPC_CHANNELS = {
  SELECTION_RESULT: 'selection:result',
  SELECTION_GET: 'selection:get',
  SELECTION_LAST: 'selection:last',
  FLOATING_SHOW: 'floating:show',
  FLOATING_HIDE: 'floating:hide',
  FLOATING_HIDDEN: 'floating:hidden',
  FLOATING_READY: 'floating:ready',
  FLOATING_RESIZE: 'floating:resize',
  LISTENER_STATUS: 'listener:status',
  LISTENER_SHORTCUT: 'listener:shortcut',
  PANEL_SHOW: 'panel:show',
  PANEL_HIDE: 'panel:hide',
  PANEL_TYPE: 'panel:type',
  PANEL_CURRENT: 'panel:current',
  PANEL_RESIZE: 'panel:resize',
  EXTERNAL_OPEN: 'external:open',
  NOTES_LIST: 'notes:list',
  NOTES_GET: 'notes:get',
  NOTES_CREATE: 'notes:create',
  NOTES_UPDATE: 'notes:update',
  NOTES_DELETE: 'notes:delete',
  NOTES_EXPORT_PDF: 'notes:export:pdf',
  NOTES_EXPORT_DOCX: 'notes:export:docx'
} as const
